experiment:
  random_seed: 1234
  num_generations: 20
  verbose: false
  cache_type: lru
  cache_size: 128
  expt_logger_enabled: true

ge:
  grammar_file: grammar.bnf
  population_size: 500
  codon_size: 127 
  max_wraps: 6
  max_recursion_depth: 10
  genome_length: 100 
  init_type: random_genome 
  mutation_probability: 0.01
  crossover_probability: 0.5
  elite_size: 3

parallel:
  parallel_enabled: true
  executor_type: "process"
  max_workers: 4
  batch_size: 10